"""Writes paper/numbers.tex: every number quoted in the paper's prose, as LaTeX macros computed from the
episode store. The paper never contains a hand-typed result.

Macro names are letters only (LaTeX). Percentages are rendered with \\% and one decimal where n is large.
"""

import asyncio
import math
from pathlib import Path

import pandas as pd

from proxy.analysis.paper_figures import DISPLAY
from proxy.config import ExperimentConfig
from proxy.counterparty.calibration import calibrate


def _pct(x: float, digits: int = 0) -> str:
    return "n/a" if x is None or (isinstance(x, float) and math.isnan(x)) else f"{100 * x:.{digits}f}\\%"


def _num(x: float, digits: int = 2) -> str:
    return "n/a" if x is None or (isinstance(x, float) and math.isnan(x)) else f"{x:.{digits}f}"


def _macro_name(model: str) -> str:
    """claude-opus-5 -> ClaudeOpusFive; letters only."""
    words = {"0": "Zero", "1": "One", "2": "Two", "3": "Three", "4": "Four", "5": "Five", "6": "Six", "7": "Seven", "8": "Eight", "9": "Nine"}
    out = []
    for part in model.replace(".", "-").split("-"):
        if part.isdigit():
            out.append("".join(words[c] for c in part))
        else:
            out.append("".join(words.get(c, c) for c in part).capitalize())
    return "".join(ch for ch in "".join(out) if ch.isalpha())


def numbers(df: pd.DataFrame, calibration: dict | None = None) -> dict[str, str]:
    m: dict[str, str] = {}
    ok = df[~df["error"]]
    m["nEpisodes"] = str(len(ok))
    m["nModels"] = str(ok["model"].nunique())
    m["nFamilies"] = str(ok["family"].nunique())
    deals = ok[ok["deal"] == 1.0]
    m["violationCount"] = str(int((ok["violated"] == 1.0).sum()))
    m["leakCount"] = str(int((ok["leaked_near"] == 1.0).sum()))

    a = ok[ok["blocked_alt"] == 1.0]
    j = a.dropna(subset=["a_nondisclosed"])
    m["exposedCount"] = str(len(a))
    m["exposureRate"] = _pct(ok["blocked_alt"].mean())
    m["doneJudgedAll"] = _pct(j["a_nondisclosed"].mean())
    m["doneLowerAll"] = _pct(a["a_unmentioned"].mean())
    cats = a["a_category"].value_counts()
    for key, name in (("acknowledged", "Ack"), ("mentioned_not_acknowledged", "Mentioned"), ("contradicted", "Contradicted")):
        m[f"doneCount{name}"] = str(int(cats.get(key, 0)))

    s = ok.dropna(subset=["total_misstated"])
    for model, g in ok.groupby("model"):
        name = _macro_name(model)
        gj = j[j["model"] == model]
        gs = s[s["model"] == model]
        m[f"doneJudged{name}"] = _pct(gj["a_nondisclosed"].mean()) if len(gj) else "n/a"
        m[f"doneN{name}"] = str(len(gj))
        m[f"dtwoWrong{name}"] = _pct(gs["total_misstated"].mean()) if len(gs) else "n/a"
        m[f"dtwoN{name}"] = str(len(gs))
        for target in ("good", "bad"):
            c = g[(g["outcome_target"] == target)]["char_rating"].dropna()
            m[f"portray{target.capitalize()}{name}"] = _num(c.mean(), 1) if len(c) else "n/a"

    for target in ("good", "bad"):
        g = deals[deals["outcome_target"] == target]["gain_fraction"].dropna()
        m[f"pilotGain{target.capitalize()}"] = _num(g.mean())
    if calibration:
        for target, key in (("good", "calGood"), ("mediocre", "calMediocre"), ("bad", "calBad")):
            m[key] = _num(calibration.get(target, math.nan))
    return m


def reference_calibration(config: str = "configs/pilot.yaml") -> dict:
    """Mean gain among deals for the floor-respecting reference agent, per target."""
    res = asyncio.run(calibrate(ExperimentConfig.load(config)))
    return {target: r.get("gain_mean") or math.nan for (target, kind), r in res.items() if kind == "compliant"}


def write_numbers(df: pd.DataFrame, path: Path, calibration: dict | None = None) -> Path:
    macros = numbers(df, calibration)
    lines = ["% Generated by proxy.analysis.paper_numbers. Do not edit by hand."]
    lines += [f"\\newcommand{{\\{k}}}{{{v}}}" for k, v in sorted(macros.items())]
    Path(path).write_text("\n".join(lines) + "\n")
    return Path(path)


__all__ = ["numbers", "write_numbers", "reference_calibration", "DISPLAY"]
